[build]
  base    = "mundoalfa-react"
  command = "npm run build"
  publish = ".next"

[functions]
  # Como tu config usa [build].base = "mundoalfa-react",
  # referenciá el archivo desde esa carpeta base:
  included_files = ["lib/mundoAlfa.db"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
